/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class NuevaFactura extends javax.swing.JFrame {

    /**
     * Creates new form NuevaFactura
     */
    public NuevaFactura() {
        initComponents();
    }

    public JButton getBtnCancelar() {
        return BtnCancelar;
    }

    public void setBtnCancelar(JButton BtnCancelar) {
        this.BtnCancelar = BtnCancelar;
    }

    public JButton getBtnGuardar() {
        return BtnGuardar;
    }

    public void setBtnGuardar(JButton BtnGuardar) {
        this.BtnGuardar = BtnGuardar;
    }

    public JComboBox<String> getComboBoxTipoPago() {
        return ComboBoxTipoPago;
    }

    public void setComboBoxTipoPago(JComboBox<String> ComboBoxTipoPago) {
        this.ComboBoxTipoPago = ComboBoxTipoPago;
    }

    public JPanel getJPNuevaFcatura() {
        return JPNuevaFcatura;
    }

    public void setJPNuevaFcatura(JPanel JPNuevaFcatura) {
        this.JPNuevaFcatura = JPNuevaFcatura;
    }

    public JTextField getTxt() {
        return Txt;
    }

    public void setTxt(JTextField Txt) {
        this.Txt = Txt;
    }

    public JTextField getTxtIdentificacionProvee() {
        return TxtIdentificacionProvee;
    }

    public void setTxtIdentificacionProvee(JTextField TxtIdentificacionProvee) {
        this.TxtIdentificacionProvee = TxtIdentificacionProvee;
    }

    public JTextField getTxtIdentificacionUsu() {
        return TxtIdentificacionUsu;
    }

    public void setTxtIdentificacionUsu(JTextField TxtIdentificacionUsu) {
        this.TxtIdentificacionUsu = TxtIdentificacionUsu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNuevaFcatura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdentificarUsuario = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        TxtIdentificacionUsu = new javax.swing.JTextField();
        Txt = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        lblPago = new javax.swing.JLabel();
        ComboBoxTipoPago = new javax.swing.JComboBox<>();
        lblIdentificacionProve = new javax.swing.JLabel();
        TxtIdentificacionProvee = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Nueva Factura");

        lblIdentificarUsuario.setText("Identificacion Del Usuario");

        lblDocumento.setText("Documento");

        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BtnGuardar.setText("Guardar");

        lblPago.setText("Tipo De Pago");

        ComboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...." }));

        lblIdentificacionProve.setText("Identificacion Del Proveedor");

        BtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout JPNuevaFcaturaLayout = new javax.swing.GroupLayout(JPNuevaFcatura);
        JPNuevaFcatura.setLayout(JPNuevaFcaturaLayout);
        JPNuevaFcaturaLayout.setHorizontalGroup(
            JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNuevaFcaturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelar)
                .addGap(116, 116, 116)
                .addComponent(BtnGuardar)
                .addGap(129, 129, 129))
            .addGroup(JPNuevaFcaturaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDocumento)
                        .addComponent(lblIdentificacionProve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblIdentificarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtIdentificacionUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdentificacionProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        JPNuevaFcaturaLayout.setVerticalGroup(
            JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNuevaFcaturaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPago)
                    .addComponent(ComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtIdentificacionProvee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentificacionProve))
                .addGap(38, 38, 38)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificarUsuario)
                    .addComponent(TxtIdentificacionUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocumento))
                .addGap(64, 64, 64)
                .addGroup(JPNuevaFcaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnCancelar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JPNuevaFcatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JPNuevaFcatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> ComboBoxTipoPago;
    private javax.swing.JPanel JPNuevaFcatura;
    private javax.swing.JTextField Txt;
    private javax.swing.JTextField TxtIdentificacionProvee;
    private javax.swing.JTextField TxtIdentificacionUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblIdentificacionProve;
    private javax.swing.JLabel lblIdentificarUsuario;
    private javax.swing.JLabel lblPago;
    // End of variables declaration//GEN-END:variables
}
