/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class NuevoProveedor extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_proveedor
     */
    public NuevoProveedor() {
        initComponents();
    }

    public JButton getBtnGuardar() {
        return BtnGuardar;
    }

    public void setBtnGuardar(JButton BtnGuardar) {
        this.BtnGuardar = BtnGuardar;
    }

    public JComboBox<String> getComboBoxTipoDocu() {
        return ComboBoxTipoDocu;
    }

    public void setComboBoxTipoDocu(JComboBox<String> ComboBoxTipoDocu) {
        this.ComboBoxTipoDocu = ComboBoxTipoDocu;
    }

    public JPanel getJPproveedor() {
        return JPproveedor;
    }

    public void setJPproveedor(JPanel JPproveedor) {
        this.JPproveedor = JPproveedor;
    }

    public JLabel getNuevo_Producto() {
        return Nuevo_Proveedor;
    }

    public void setNuevo_Producto(JLabel Nuevo_Producto) {
        this.Nuevo_Proveedor = Nuevo_Producto;
    }

    public JTextField getTextDocumento() {
        return TextDocumento;
    }

    public void setTextDocumento(JTextField TextDocumento) {
        this.TextDocumento = TextDocumento;
    }

    public JTextField getTxtCorreo() {
        return TxtCorreo;
    }

    public void setTxtCorreo(JTextField TxtCorreo) {
        this.TxtCorreo = TxtCorreo;
    }

    public JTextField getTxtDirec() {
        return TxtDirec;
    }

    public void setTxtDirec(JTextField TxtDirec) {
        this.TxtDirec = TxtDirec;
    }

    public JTextField getTxtNombre() {
        return TxtNombre;
    }

    public void setTxtNombre(JTextField TxtNombre) {
        this.TxtNombre = TxtNombre;
    }

    public JTextField getTxtTelefono() {
        return TxtTelefono;
    }

    public void setTxtTelefono(JTextField TxtTelefono) {
        this.TxtTelefono = TxtTelefono;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JComboBox<String> getjComboBoxSexo() {
        return jComboBoxSexo;
    }

    public void setjComboBoxSexo(JComboBox<String> jComboBoxSexo) {
        this.jComboBoxSexo = jComboBoxSexo;
    }

    public JComboBox<String> getjComboBoxTipoPerso() {
        return jComboBoxTipoPerso;
    }

    public void setjComboBoxTipoPerso(JComboBox<String> jComboBoxTipoPerso) {
        this.jComboBoxTipoPerso = jComboBoxTipoPerso;
    }

   

    public JDateChooser getDateFecha() {
        return DateFecha;
    }

    public void setDateFecha(JDateChooser DateFecha) {
        this.DateFecha = DateFecha;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPproveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextDocumento = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        ComboBoxTipoDocu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        LblPersona = new javax.swing.JLabel();
        jComboBoxTipoPerso = new javax.swing.JComboBox<>();
        LblSexo = new javax.swing.JLabel();
        LblDireccion = new javax.swing.JLabel();
        TxtDirec = new javax.swing.JTextField();
        LblFecha = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        Nuevo_Proveedor = new javax.swing.JLabel();
        DateFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Documento");

        jLabel2.setText("Nombre");

        jLabel3.setText("Telefono");

        jLabel4.setText("Tipo de documento");

        ComboBoxTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jLabel5.setText("correo");

        LblPersona.setText("Tipo de persona");

        jComboBoxTipoPerso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        LblSexo.setText("Sexo");

        LblDireccion.setText("Direccion");

        LblFecha.setText("Fecha de nacimiento");

        btnCancelar.setBackground(new java.awt.Color(51, 51, 255));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");

        BtnGuardar.setBackground(new java.awt.Color(0, 51, 255));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione su sexo" }));

        Nuevo_Proveedor.setText("Nuevo_Proveveedor");

        javax.swing.GroupLayout JPproveedorLayout = new javax.swing.GroupLayout(JPproveedor);
        JPproveedor.setLayout(JPproveedorLayout);
        JPproveedorLayout.setHorizontalGroup(
            JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPproveedorLayout.createSequentialGroup()
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPproveedorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(ComboBoxTipoDocu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPproveedorLayout.createSequentialGroup()
                        .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(LblPersona)
                            .addComponent(LblSexo)
                            .addComponent(LblDireccion))
                        .addGap(38, 38, 38)
                        .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextDocumento)
                            .addComponent(TxtNombre)
                            .addComponent(TxtTelefono)
                            .addComponent(TxtCorreo)
                            .addComponent(jComboBoxTipoPerso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtDirec)
                            .addGroup(JPproveedorLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(93, 93, 93)
                                .addComponent(BtnGuardar)
                                .addGap(0, 157, Short.MAX_VALUE))
                            .addComponent(jComboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JPproveedorLayout.createSequentialGroup()
                        .addComponent(LblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(DateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPproveedorLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(Nuevo_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        JPproveedorLayout.setVerticalGroup(
            JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nuevo_Proveedor)
                .addGap(27, 27, 27)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBoxTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPersona)
                    .addComponent(jComboBoxTipoPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSexo)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDireccion)
                    .addComponent(TxtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPproveedorLayout.createSequentialGroup()
                        .addComponent(LblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(JPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(BtnGuardar)))
                    .addGroup(JPproveedorLayout.createSequentialGroup()
                        .addComponent(DateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JPproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JPproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> ComboBoxTipoDocu;
    private com.toedter.calendar.JDateChooser DateFecha;
    private javax.swing.JPanel JPproveedor;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblPersona;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel Nuevo_Proveedor;
    private javax.swing.JTextField TextDocumento;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDirec;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTipoPerso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

   
}
