/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Nuevo_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Producto
     */
    public Nuevo_Producto() {
        initComponents();
    }

    public JButton getBtnBuscar() {
        return BtnBuscar;
    }

    public void setBtnBuscar(JButton BtnBuscar) {
        this.BtnBuscar = BtnBuscar;
    }

   

   
    public JLabel getNuevo_Pro() {
        return Nuevo_Pro;
    }

    public void setNuevo_Pro(JLabel Nuevo_Pro) {
        this.Nuevo_Pro = Nuevo_Pro;
    }

    public JTextArea getTxtDescrip() {
        return TxtDescrip;
    }

    public void setTxtDescrip(JTextArea TxtDescrip) {
        this.TxtDescrip = TxtDescrip;
    }

    public JTextField getTxtImagen() {
        return TxtImagen;
    }

    public void setTxtImagen(JTextField TxtImagen) {
        this.TxtImagen = TxtImagen;
    }

    public JTextField getTxtNombre() {
        return TxtNombre;
    }

    public void setTxtNombre(JTextField TxtNombre) {
        this.TxtNombre = TxtNombre;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JPanel getJPproveedor() {
        return JPproducto;
    }

    public void setJPproveedor(JPanel JPproveedor) {
        this.JPproducto = JPproveedor;
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPproducto = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtImagen = new javax.swing.JTextField();
        descripcion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDescrip = new javax.swing.JTextArea();
        BtnBuscar = new javax.swing.JButton();
        Nuevo_Pro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPproducto.setBackground(new java.awt.Color(255, 204, 204));

        nombre.setText("Nombre");

        imagen.setText("Imagen");

        descripcion.setText("Descripcion");

        btnCancelar.setBackground(new java.awt.Color(51, 204, 255));
        btnCancelar.setText("Cancelar");

        btnGuardar.setBackground(new java.awt.Color(0, 204, 255));
        btnGuardar.setText("Guardar");

        TxtDescrip.setColumns(20);
        TxtDescrip.setRows(5);
        jScrollPane1.setViewportView(TxtDescrip);

        BtnBuscar.setText("Buscar");

        Nuevo_Pro.setText("Nuevo Producto");

        javax.swing.GroupLayout JPproductoLayout = new javax.swing.GroupLayout(JPproducto);
        JPproducto.setLayout(JPproductoLayout);
        JPproductoLayout.setHorizontalGroup(
            JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPproductoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(imagen)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNombre)
                    .addComponent(jScrollPane1)
                    .addGroup(JPproductoLayout.createSequentialGroup()
                        .addComponent(TxtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
            .addGroup(JPproductoLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btnCancelar)
                .addGap(92, 92, 92)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPproductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nuevo_Pro)
                .addGap(292, 292, 292))
        );
        JPproductoLayout.setVerticalGroup(
            JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPproductoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Nuevo_Pro)
                .addGap(53, 53, 53)
                .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imagen)
                        .addComponent(TxtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPproductoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(descripcion))
                    .addGroup(JPproductoLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(JPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JPproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JPanel JPproducto;
    private javax.swing.JLabel Nuevo_Pro;
    private javax.swing.JTextArea TxtDescrip;
    private javax.swing.JTextField TxtImagen;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables




   
}
